[workspace]
resolver = "2"
members = [
    "tiki-client",
    "tiki-editor",
    "tiki-input",
    "tiki-macros",
    "tiki-proto",
    "tiki-render",
    "tiki-world",
]

[workspace.lints.clippy]
new_without_default = "allow"
