[package]
name = "tiki-macros"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.76", features = ["full"] }
proc-macro2 = "1.0.86"
