[package]
name = "tiki-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.5"
tiki-render = { path = "../tiki-render" }
egui = "0.29.1"
egui-winit = "0.29.1"
egui-wgpu = "0.29.1"
wgpu = "22.1.0"

[lints]
workspace = true
