[package]
name = "tiki-proto"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"

[lints]
workspace = true

[dependencies]
tiki-macros = { path = "../tiki-macros" }

byteorder = "1.5.0"
thiserror = "1.0.63"
bitflags = "2.6.0"
